name: Build libc++_shared.so (16K) for Android

on:
  workflow_dispatch:

jobs:
  build-libcxx:
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 21
      ABI: arm64-v8a

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build git wget unzip

    - name: Download latest Android NDK
      run: |
        NDK_VERSION=r26b
        wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -O ndk.zip
        unzip ndk.zip -d $HOME/android-ndk
        echo "NDK_PATH=$HOME/android-ndk/android-ndk-$NDK_VERSION" >> $GITHUB_ENV

    - name: Clone LLVM libc++ & libc++abi
      run: |
        git clone https://github.com/llvm/llvm-project.git llvm-project --depth 1
        mkdir build_libcxxabi build_libcxx

    - name: Build libc++abi
      run: |
        cmake -S llvm-project/libcxxabi -B build_libcxxabi \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=$ANDROID_API \
          -DCMAKE_BUILD_TYPE=Release \
          -DLIBCXXABI_ENABLE_SHARED=ON \
          -DLIBCXXABI_USE_COMPILER_RT=ON \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000"
        cmake --build build_libcxxabi

    - name: Build libc++_shared.so
      run: |
        cmake -S llvm-project/libcxx -B build_libcxx \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=$ANDROID_API \
          -DCMAKE_BUILD_TYPE=Release \
          -DLIBCXX_ENABLE_SHARED=ON \
          -DLIBCXX_ENABLE_STATIC=OFF \
          -DLIBCXX_CXX_ABI=libcxxabi \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXXABI_LIBCXXABI_LIBRARY=$(pwd)/build_libcxxabi/libc++abi.so \
          -DLIBCXXABI_LIBCXXABI_INCLUDE_PATHS=$(pwd)/llvm-project/libcxxabi/include \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000" \
          -DCMAKE_CXX_FLAGS="-fPIC"
        cmake --build build_libcxx

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libc++_shared_16k
        path: build_libcxx/lib/cxx/libc++_shared.so
