name: Build libc++_shared v7a Optimized

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # 推荐使用较新的稳定版 NDK
      NDK_VERSION: r21d # 或 r25c, r26b 等
      ABI: armeabi-v7a
      ANDROID_API: 21
      BUILD_DIR: build
      # 定义 NDK 路径，方便后续引用
      NDK_ROOT: $HOME/android-ndk

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: llvmorg-12.0.0 # 保持 12.0.0，如果仍然有问题，可以尝试更新
        path: llvm-project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip curl

    - name: Download NDK
      run: |
        # 针对 NDK 25.2.9519653 的下载链接
        curl -LO https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux-x86_64.zip
        unzip android-ndk-r${NDK_VERSION}-linux-x86_64.zip -d $HOME
        mv $HOME/android-ndk-r${NDK_VERSION} $NDK_ROOT
        # 清理 zip 包
        rm android-ndk-r${NDK_VERSION}-linux.zip

    - name: Configure CMake (armeabi-v7a)
      run: |
        # 获取 NDK 中的 Clang 编译器路径
        export TOOLCHAIN_BIN=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin
        export CXX=$TOOLCHAIN_BIN/armv7a-linux-androideabi$ANDROID_API-clang++
        export CC=$TOOLCHAIN_BIN/armv7a-linux-androideabi$ANDROID_API-clang
        export AR=$TOOLCHAIN_BIN/llvm-ar
        export RANLIB=$TOOLCHAIN_BIN/llvm-ranlib
        export STRIP=$TOOLCHAIN_BIN/llvm-strip

        mkdir -p $BUILD_DIR

        cmake -S llvm-project/runtimes -B $BUILD_DIR \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_ROOT/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=$ANDROID_API \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
          -DLIBCXX_ENABLE_SHARED=ON \
          -DLIBCXX_ENABLE_STATIC=OFF \
          -DLIBCXXABI_ENABLE_SHARED=ON \
          -DLIBCXXABI_ENABLE_STATIC=OFF \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXX_USE_COMPILER_RT=ON \
          -DLIBCXX_INCLUDE_TESTS=OFF \
          -DCMAKE_C_FLAGS="-fPIC -Wno-cast-qual -Wno-error" \
          -DCMAKE_CXX_FLAGS="-fPIC -Wno-cast-qual -Wno-error -std=c++17 -D_LIBCPP_HAS_MUSL_LIBC" \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000" \
          -DCMAKE_SYSROOT=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot

    - name: Build libc++_shared
      run: cmake --build $BUILD_DIR --target cxxabi_shared cxx_shared -j$(nproc)

    - name: Package artifact
      uses: actions/upload-artifact@v4
      with:
        name: libcxx-v7a-optimized
        path: $BUILD_DIR/lib/*.so
