name: Build libc++_shared armeabi-v7a (16KB aligned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: r21d
      ANDROID_API: 21
      ANDROID_ABI: armeabi-v7a
      ALIGNMENT: 16384

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip
        unzip android-ndk-${{ env.NDK_VERSION }}-linux-x86_64.zip -d $HOME
        mv $HOME/android-ndk-${{ env.NDK_VERSION }} $HOME/android-ndk

    - name: Set NDK environment
      run: |
        export ANDROID_NDK_HOME=$HOME/android-ndk
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Create build directory
      run: mkdir -p build-armeabi-v7a

    - name: Configure CMake
      run: |
        cmake -B build-armeabi-v7a \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ env.ANDROID_ABI }} \
          -DANDROID_PLATFORM=android-${{ env.ANDROID_API }} \
          -DANDROID_STL=c++_shared \
          -DCMAKE_BUILD_TYPE=Release \
          -DLIBCXXABI_ENABLE_SHARED=ON \
          -DLIBCXX_ENABLE_SHARED=ON \
          -DLIBCXXABI_USE_LLVM_UNWINDER=ON \
          -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF

    - name: Build libc++_shared
      run: cmake --build build-armeabi-v7a --target cxx_shared -- -j$(nproc)

    - name: Align .so to 16KB
      run: |
        mkdir -p aligned
        for f in build-armeabi-v7a/lib/*.so; do
          llvm-objcopy --segment-alignment=${{ env.ALIGNMENT }} "$f" "aligned/$(basename $f)"
        done

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: libcxx_shared_armeabi-v7a_16kb
        path: aligned/
