name: Build libc++_shared v7a 16K

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r26b
      ABI: armeabi-v7a
      ANDROID_API: 21

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: llvmorg-17.0.6  # 或者你想要的版本
        path: llvm-project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip curl

    - name: Download NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip
        unzip android-ndk-${NDK_VERSION}-linux.zip
        mv android-ndk-${NDK_VERSION} $HOME/android-ndk

    - name: Configure CMake
      run: |
        cmake -S llvm-project/runtimes -B build \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=$ANDROID_API \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
          -DLIBCXX_ENABLE_SHARED=ON \
          -DLIBCXX_ENABLE_STATIC=OFF \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000" \
          -DCMAKE_CXX_FLAGS="-fPIC"

    - name: Build
      run: cmake --build build

    - name: Package artifact
      uses: actions/upload-artifact@v4
      with:
        name: libcxx-v7a-16k
        path: build/**/*.so
