name: Build libcxx v7a 16KB
on:
  workflow_dispatch:

jobs:
  build-libcxx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up NDK r21d
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d

      - name: Build libc++_shared.so (armeabi-v7a)
        run: |
          ABI=armeabi-v7a
          ANDROID_API=24
          cmake -S llvm-project/libcxx -B build_libcxx \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=$ABI \
            -DANDROID_PLATFORM=$ANDROID_API \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBCXX_ENABLE_SHARED=ON \
            -DLIBCXX_ENABLE_STATIC=OFF \
            -DLIBCXX_CXX_ABI=libcxxabi \
            -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
            -DLIBCXXABI_LIBCXXABI_INCLUDE_PATHS=$(pwd)/llvm-project/libcxxabi/include \
            -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000" \
            -DCMAKE_CXX_FLAGS="-fPIC"
          cmake --build build_libcxx

      - name: Upload libc++_shared.so
        uses: actions/upload-artifact@v4
        with:
          name: libcxx-v7a-16k
          path: build_libcxx/libc++_shared.so
