name: Build libc++_shared v7a Optimized

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: r21d
      ABI: armeabi-v7a
      ANDROID_API: 21
      BUILD_DIR: build

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        ref: llvmorg-12.0.0
        path: llvm-project

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake unzip curl

    - name: Download NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip
        unzip android-ndk-${NDK_VERSION}-linux-x86_64.zip
        mv android-ndk-${NDK_VERSION} $HOME/android-ndk

    - name: Configure CMake (armeabi-v7a)
      run: |
        # 确定工具链和sysroot路径
        TOOLCHAIN_ROOT=$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64
        SYSROOT=$TOOLCHAIN_ROOT/sysroot

        cmake -S llvm-project/runtimes -B $BUILD_DIR \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=$ANDROID_API \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
          -DLIBCXX_ENABLE_SHARED=ON \
          -DLIBCXX_ENABLE_STATIC=OFF \
          -DLIBCXXABI_ENABLE_SHARED=ON \
          -DLIBCXXABI_ENABLE_STATIC=OFF \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXX_USE_COMPILER_RT=ON \
          -DLIBCXX_INCLUDE_TESTS=OFF \
          -DCMAKE_C_FLAGS="-fPIC -Wno-cast-qual -Wno-error" \
          -DCMAKE_CXX_FLAGS="-fPIC -Wno-cast-qual -Wno-error" \
          -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,max-page-size=0x4000" \
          -DCMAKE_SYSROOT=$SYSROOT

    - name: Build libc++_shared
      run: cmake --build $BUILD_DIR --target cxxabi_shared cxx_shared -j$(nproc)

    - name: Package artifact
      uses: actions/upload-artifact@v4
      with:
        name: libcxx-v7a-optimized
        path: $BUILD_DIR/**/*.so
